### PR TITLE
Fix parent

### PR DESCRIPTION
**Pull request by ghost**
FIx config window being unresizable and crossing screen borders

Removing zip files (use GitHub releases)

### CODE REVIEW

**Comment by Jellby** [comment]
Thank you. This looks like a pretty trivial fix (you can tell I'm not an expert python or Qt programmer). I'll think about the relases, but not before the weekend.

**Comment by ghost** [comment]
I have made another commit that should definitely fix the issue (the previous one fixed the issue, but it reappeared after you try to resize the config window)

I think that calibre's TextEdit widget is bugged. In fact, after some experiements, it can be proved that:
1. This issue is not present if you use standard Qt widget like QPlainTextEdit or QTextEdit
2. This issue is not present if you use calibre's PlainTextEdit
3. This issue is not present if, in texteditwithtooltip.py, you redefine apply_theme to change how it handles size_hint. The new definition will look like that:

```
def apply_theme(self, theme):
        print("apply_theme called")
        self.theme = theme
        pal = self.palette()
        pal.setColor(pal.Base, theme_color(theme, 'Normal', 'bg'))
        pal.setColor(pal.AlternateBase, theme_color(theme, 'CursorLine', 'bg'))
        pal.setColor(pal.Text, theme_color(theme, 'Normal', 'fg'))
        pal.setColor(pal.Highlight, theme_color(theme, 'Visual', 'bg'))
        pal.setColor(pal.HighlightedText, theme_color(theme, 'Visual', 'fg'))
        self.setPalette(pal)
        self.tooltip_palette = pal = QPalette()
        pal.setColor(pal.ToolTipBase, theme_color(theme, 'Tooltip', 'bg'))
        pal.setColor(pal.ToolTipText, theme_color(theme, 'Tooltip', 'fg'))
        self.line_number_palette = pal = QPalette()
        pal.setColor(pal.Base, theme_color(theme, 'LineNr', 'bg'))
        pal.setColor(pal.Text, theme_color(theme, 'LineNr', 'fg'))
        pal.setColor(pal.BrightText, theme_color(theme, 'LineNrC', 'fg'))
        self.match_paren_format = theme_format(theme, 'MatchParen')
        font = self.font()
        print("Font: "+str(font))
        ff = tprefs['editor_font_family']
        if ff is None:
            ff = default_font_family()
        font.setFamily(ff)
        print("Font family: "+str(ff))
        
        point_size = tprefs['editor_font_size']
        font.setPointSize(point_size)
        print("Point size: "+str(point_size))
        
        self.tooltip_font = QFont(font)
        self.tooltip_font.setPointSize(font.pointSize() - 1)
        self.setFont(font)
        self.highlighter.apply_theme(theme)
        w = self.fontMetrics()
        self.number_width = max(map(lambda x:w.width(str(x)), xrange(10)))
        
        # ORIGINAL DEFINITION
        #self.size_hint = QSize(self.expected_geometry[0] * w.averageCharWidth(), self.expected_geometry[1] * w.height())
        #NEW DEFINITION
        self.size_hint = QSize(self.expected_geometry[0], self.expected_geometry[1])
        print("New size_hint is: "+str(self.size_hint))
        print("self.expected_geometry is: "+str(self.expected_geometry))
        print("w.averageCharWidth(): "+str(w.averageCharWidth()))
        print("w.height(): "+str(w.fontHeight()))
        
        self.highlight_color = theme_color(theme, 'HighlightRegion', 'bg')
        self.highlight_cursor_line()
        self.completion_popup.clear_caches(), self.completion_popup.update()

```

**Comment by Jellby** [comment]
Please remove trailing blanks and unnecessary new lines. Also, to keep things clean (not addressing multiple unrelated issues in a single PR), add back the zip files.

Or, if you don't mind, I can apply the patch in a separate commit instead of accepting this PR.

**Comment by ghost** [comment]
Yes don't worry :)

**Comment by Jellby** [comment]
OK, changes have been ported. I hope everything works as intended.

**Comment by ghost** [comment]
Yes, thanks for the citation in the changelog

**Pull request closed without merging**
